# XGo Agent 配置文件示例
# 复制此文件为 config.yaml 并填入实际的值

server:
  port: 8080
  # GitHub webhook 签名验证密钥，用于验证请求的真实性
  # 需要与 GitHub webhook 配置中的 secret 保持一致
  webhook_secret: "your_webhook_secret"

github:
  token: "your_github_token"
  webhook_url: "https://your-domain.com/webhook"

workspace:
  base_dir: "./workspaces"
  cleanup_after: "24h"

claude:
  api_key: "your_claude_api_key"
  base_url: "https://api.anthropic.com"
  container_image: "anthropic/claude:latest"
  timeout: "30s"
  interactive: true

gemini:
  api_key: "your_gemini_api_key"
  timeout: "30s"
  container_image: "gcr.io/generative-ai/generative-ai:latest"
  google_cloud_project: "your_project_id"

docker:
  socket: "/var/run/docker.sock"
  network: "bridge"

# 代码提供者配置
code_provider: "claude"
use_docker: false

# 新增 Prompt 配置
prompt:
  templates_dir: "./config/templates"
  validators_dir: "./config/validators"
  max_length: 8000
  enable_cache: true
